---
# Secrets Setup (Age Key Transfer)

- name: Create secrets directory
  file:
    path: "{{ age_key_path }}"
    state: directory
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: '0700'

- name: Transfer age encryption key
  copy:
    content: "{{ lookup('file', age_key_source) }}"
    dest: "{{ age_key_path }}/keys.txt"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: '0600'
  no_log: false

- name: Create symlink to age key in app directory
  file:
    src: "{{ age_key_path }}/keys.txt"
    dest: "{{ app_directory }}/app/infra/secrets/keys/age-prod.key"
    state: link
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    force: yes
